update to now folder for external essets

diff --git a/now/bin/dl b/now/bin/dl
--- a/now/bin/dl
+++ b/now/bin/dl
@@ -1,27 +1,50 @@
 #!/bin/bash
 
+# sudo date -s "03 feb 2024 4:20 am"; ###############
 ################################################## For learning more: https://timeapi.io/swagger/index.html ##################################################
-sudo date -s "03 feb 2024 4:20 am"; ###############
 
-sleep 2;
+# sleep 2;
 
-API_URL="https://timeapi.io/api/Time/current/zone?timeZone=Asia/Dhaka"
+# API_URL="https://timeapi.io/api/Time/current/zone?timeZone=Asia/Dhaka"
 
-response=$(curl -s "$API_URL")
+# response=$(curl -s "$API_URL")
 
-if [ -z "$response" ]; then
-  echo "Error: Failed to fetch data from the API."
-  exit 1
-fi
+# if [ -z "$response" ]; then
+#   echo "Error: Failed to fetch data from the API."
+#   exit 1
+# fi
 
-# Parse the response using jq (make sure jq is installed)
-numaric_date=$(echo "$response" | jq '.date')
-day=$(echo "$response" | jq '.day')
-month=$(echo "$response" | jq '.month')
-year=$(echo "$response" | jq '.year')
-time_24=$(echo "$response" | jq '.time')
-time_zone=$(echo "$response" | jq '.timeZone')
-name_of_week=$(echo "$response" | jq '.dayOfWeek')
+# # Parse the response using jq (make sure jq is installed)
+# numaric_date=$(echo "$response" | jq '.date')
+# day=$(echo "$response" | jq '.day')
+# month=$(echo "$response" | jq '.month')
+# year=$(echo "$response" | jq '.year')
+# time_24=$(echo "$response" | jq '.time')
+# time_zone=$(echo "$response" | jq '.timeZone')
+# name_of_week=$(echo "$response" | jq '.dayOfWeek')
+
+####################################################################################################
+# Get the current year
+year=$(date +"%Y")
+
+# Get the current month
+month=$(date +"%-m") # Remove leading zero
+
+# Get the current day
+day=$(date +"%-d") # Remove leading zero
+
+# Get the current date in MM/DD/YYYY format
+numaric_date=$(date +"%m/%d/%Y")
+
+# Get the current time in HH:MM format
+time_24=$(date +"%H:%M")
+
+# Get the time zone
+# timeZone=$(date +"%Z")
+time_zone="Asia/Dhaka"
+
+# Get the day of the week
+name_of_week=$(date +"%A")
 
 # echo $(( $(date +%u --date="Wednesday") % 7 + 1 ))
 # number_of_week=$(echo $(( $(date +%u --date=${name_of_week//\"/}) % 7 + 1 )))
@@ -40,28 +63,31 @@ whole_time=$(date -d "$year-$month-$day ${time_24//\"/}" +"%I:%M %p") # 24h to 1
 day_of_the_year=$(date -d $year-$month-$day '+%j') # Output: number
 week_of_the_year=$((${day_of_the_year#0} / 7)) # Exluding 0 for non-octal interpretation
 
-sudo date -s "$year-$month-$day $whole_time" #############
+# sudo date -s "$year-$month-$day $whole_time" #############
 
 am_pm_part=$(echo $whole_time | rev | cut -c 1-2 | rev)  
 hour_part=$(echo $whole_time | cut -c 1-2)
 min_part=$(echo $whole_time | cut -c 4-5)
 
-if [[ "${am_pm_part//\"/}" == "PM" ]];  
-then 
-  hour_passed=$(expr ${hour_part#0} + 6) # Starting time: 6:00 AM
-  hour_left=$((16 - ${hour_passed#0})) # 6:00 AM - 10:00 PM = 16h 
-  min_left=$((60 - ${min_part#0}))
-fi
+###################################################################
+# if [[ "${am_pm_part//\"/}" == "PM" ]];  
+# then 
+#   hour_passed=$(expr ${hour_part#0} + 6) # Starting time: 6:00 AM
+#   hour_left=$((16 - ${hour_passed#0})) # 6:00 AM - 10:00 PM = 16h 
+#   min_left=$((60 - ${min_part#0}))
+# fi
 
-if [[ "${am_pm_part//\"/}" == "AM" ]];  
-then 
-  if [[ $hour_part -gt 5 ]];  
-  then 
-    hour_passed=$(expr ${hour_part#0} - 6) # Starting from 6:00 AM
-    hour_left=$((16 - ${hour_passed#0})) # 6:00 AM - 10:00 PM = 16h
-    min_left=$((60 - ${min_part#0}))
-  fi
-fi
+# if [[ "${am_pm_part//\"/}" == "AM" ]];  
+# then 
+#   if [[ $hour_part -gt 5 ]];  
+#   then 
+#     hour_passed=$(expr ${hour_part#0} - 6) # Starting from 6:00 AM
+#     hour_left=$((16 - ${hour_passed#0})) # 6:00 AM - 10:00 PM = 16h
+#     min_left=$((60 - ${min_part#0}))
+#   fi
+# fi
+
+#################################################################
 
 date_no=$(echo $letter_month_and_date | rev | cut -c 1-2 | rev)  
 
@@ -104,11 +130,24 @@ fi
 # fi
 
 
-echo "---------+---------+---------+---------+---------+---------+---------"
 # echo "Time Zone: $time_zone"
 # echo "Time: $whole_time"
 # echo "Time has left: ${hour_left}h ${min_left}m"
 # echo "Time has passed: ${hour_passed}h ${min_part}m/17h"
+
+#################################################
+current_24_time=$(date +"%H:%M")
+current_12_time=$(date +"%I:%M %p")
+# time1=$(/home/fahmida/.local/bin/time_passed_left "${fair//\"/}")
+echo_left_and_passed=$(/home/fahmida/.local/bin/time_passed_left "${current_24_time//\"/}")
+
+
+###################################################
+
+echo "Time Zone: $time_zone"
+echo "Time: $current_12_time"
+echo "$echo_left_and_passed"
+echo "---------+---------+---------+---------+---------+---------+---------"
 echo "Today: $letter_month_and_date        $which_week out of 4 weeks"
 # echo "Month of The Year: $month"
 echo "Month: $month"
@@ -118,4 +157,5 @@ echo "Days has passed: $day_of_the_year days passed"
 echo "Weeks has passed: $week_of_the_year weeks passed"
 # echo "Day Of The Week: ${number_of_week}th day week"
 echo "---------+---------+---------+---------+---------+---------+---------"
+
 
